---
# handlers file for kubernetes_master
- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Restart kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

- name: Restart Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
