---
- name: Disable SWAP (Kubeadm requirement)
  shell: |
    swapoff -a

- name: Disable SWAP in fstab (Kubeadm requirement)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  register: kubeadm_output

- name: Set up kubectl for the current user
  command: "{{ item }}"
  with_items:
    - "mkdir -p $HOME/.kube"
    - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
    - "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Install Calico network plugin
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    when: "'calico' in kubeadm_output.stdout"