---
- name: Prepare Kubernetes cluster
  hosts: all
  become: true
  roles:
    - kubernetes_node

- name: Configure Kubernetes Master
  hosts: master_nodes
  become: true
  roles:
    - kubernetes_master

- name: Configure Kubernetes Network
  hosts: master_nodes
  roles:
    - kubernetes_network

- name: Configure Kubernetes Worker
  hosts: worker_nodes
  become: true
  roles:
    - kubernetes_worker
