---
# handlers file for kubernetes_node
- name: Reload sysctl
  command: sysctl --system

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: Restart kubelet service
  systemd:
    name: kubelet
    state: restarted

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
