---
# tasks file for kubernetes_node
- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Remove Existing Kubernetes Directory (if it exists)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pkgs_k8s_io_core_stable_v{{ kubernetes_version }}_deb.list
    state: absent

- name: Check if swap is enabled
  ansible.builtin.command: swapon --summary
  register: swap_status
  changed_when: false

- name: Disable swap if enabled
  ansible.builtin.command: swapoff -a
  when: swap_status.stdout_lines | length > 0
  changed_when: swap_status.stdout_lines | length > 0

- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Add kernel modules for Containerd
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load kernel modules for Containerd
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Add kernel parameters for Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    mode: '0644'
  notify:
    - Reload sysctl

- name: Configuring Containerd (building the configuration file)
  ansible.builtin.command:
    cmd: sh -c "containerd config default > /opt/containerd/config.toml"
  args:
    creates: /opt/containerd/config.toml

- name: Configuring Containerd (Setting SystemdCgroup Variable to True)
  ansible.builtin.lineinfile:
    path: /opt/containerd/config.toml
    regexp: '^SystemdCgroup = false'
    line: 'SystemdCgroup = true'
  notify:
    - Restart containerd service

- name: Ensure UFW is started and enabled
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: true

- name: Enable the firewall
  community.general.ufw:
    state: enabled

- name: Allow required ports through firewall
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - {port: 22, proto: tcp}
    - {port: 53, proto: tcp}
    - {port: 53, proto: udp}
    - {port: 6443, proto: tcp}
    - {port: 2379:2380, proto: tcp}
    - {port: 8080, proto: tcp}
    - {port: 10250, proto: tcp}
    - {port: 10251, proto: tcp}
    - {port: 10252, proto: tcp}
    - {port: 10255, proto: tcp}
    - {port: 30080, proto: tcp}
    - {port: 30880, proto: tcp}

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'

- name: Convert Kubernetes GPG key to keyring format
  ansible.builtin.command:
    cmd: >
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present

- name: Install Kubernetes components
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Hold kubelet, kubeadm, kubectl packages
  ansible.builtin.command:
    cmd: apt-mark hold "{{ item }}"
  loop:
    - kubelet
    - kubeadm
    - kubectl
  changed_when: false

- name: Ensure kubelet is started and enabled
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true

- name: Replace /etc/default/kubelet contents
  ansible.builtin.copy:
    dest: /etc/default/kubelet
    content: 'KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs"'
    mode: '0644'
  notify:
    - Restart kubelet service
