name: "Ansible Linting"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  ansible-lint:
    name: 'Lint Ansible'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install ansible-lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint

    - name: Run ansible-lint
      run: |
        ansible-lint ./site.yaml
      working-directory: ansible

